version: "3.8"
services:
  mano:
    image: mano-detector:py3.10
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
